sudo: required

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++

before_install:
  - sudo apt-get install cmake libevent-dev
  - git clone https://github.com/CopernicaMarketingSoftware/AMQP-CPP.git
  - cd AMQP-CPP
  - mkdir build
  - cd build
  - cmake -DAMQP-CPP_BUILD_EXAMPLES=OFF -DAMQP-CPP_LINUX_TCP=ON -DCMAKE_BUILD_TYPE:STRING=RELEASE ..
  - make && sudo make install

# Build steps
script:
  - cd ../..
  - make