sudo: required
# before_install:
#   - sudo apt-get install libao-dev
#   - sudo apt-get install libcurl4-openssl-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++

before_install:
  - sudo apt-get install cmake
  - git clone https://github.com/CopernicaMarketingSoftware/AMQP-CPP.git
  - cd AMQP-CPP
  - mkdir build
  - cd build
  - cmake -DAMQP-CPP_BUILD_EXAMPLES=OFF -DAMQP-CPP_LINUX_TCP=ON ..
  - make && make install

# Build steps
script:
  - make